name: test
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0=py39h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py39haa95532_0
  - cffi=1.15.0=py39h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - codecov=2.1.11=pyhd3eb1b0_0
  - coverage=5.5=py39h2bbff1b_2
  - cryptography=35.0.0=py39h71e12ea_0
  - idna=3.3=pyhd3eb1b0_0
  - openssl=1.1.1l=h2bbff1b_0
  - pip=21.2.4=py39haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.7=h6244533_1
  - requests=2.26.0=pyhd3eb1b0_0
  - setuptools=58.0.4=py39haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py39haa95532_0
  - wincertstore=0.2=py39haa95532_2
prefix: C:\Users\HannaVincent\anaconda3\envs\test
