[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-formtools = "==1.0"
djangorestframework = "==3.10.1"
django-filter = "==2.2.0"
django-widget-tweaks = "==1.4.1"
phonenumbers = "==8.9.10"
pytz = "==2018.5"
requests = "==2.20.0"
Django = "==1.11.22"
Markdown = "==3.1.1"
Pygments = "==2.2.0"
threadfix_api = "==1.1.1"

[dev-packages]

[requires]
python_version = "3.9"
